name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Create Vendor Directory
        run: |
          echo Making directory...
          mkdir vendor
          echo Directory made.
          sed "s/^zend_extension=.*opcache.so/zend_extension=$(find $(pwd) -name opcache.so | sed 's/\//\\\//g')/g" bin/php7/bin/php.ini | tee bin/php7/bin/php.ini
      - name: Run PHPStan
        uses: nxtlvlsoftware/pmmp-phpstan-action@3
        with:
          phpstan-config: phpstan.neon.dist
